"""Tests for the linear (no-ODE-fitting) inertial parameter estimators,
validated against synthetic trajectories generated by the rigid-body
integrator itself -- a strong self-consistency check, since the estimator
and the simulator are independent code paths sharing only the physics."""

from __future__ import annotations

import numpy as np
import pytest

from ballast.identify.linear_tumble import (
    com_from_free_flight,
    inertia_from_angular_momentum,
)
from ballast.physics.rigid import RigidBodyState, free_flight_force, integrate

I_ASYMMETRIC = np.diag([1.0, 2.0, 3.0])


def test_recovers_inertia_ratios_from_genuine_npa_tumble():
    """A genuinely non-principal-axis tumble should let the SVD solver
    recover the correct principal-axis ratios, up to the theorem's
    unavoidable scale ambiguity."""
    state0 = RigidBodyState(
        position_m=np.zeros(3),
        velocity_m_s=np.zeros(3),
        quaternion=np.array([1.0, 0.0, 0.0, 0.0]),
        omega_body_rad_s=np.array([0.3, 4.0, 0.1]),
    )
    traj = integrate(state0, m=1.0, i_body=I_ASYMMETRIC, dt=0.001, n_steps=5000)

    # subsample: adjacent frames are highly correlated and add little new
    # information to the differenced linear system
    idx = np.arange(0, 5001, 20)
    rotations = traj.rotation_matrices()[idx]
    omegas = traj.omega_body_rad_s[idx]

    result = inertia_from_angular_momentum(rotations, omegas)

    true_ratios = np.sort(np.diag(I_ASYMMETRIC)) / np.max(np.diag(I_ASYMMETRIC))
    assert np.allclose(result.principal_ratios, true_ratios, atol=0.02)

    # a genuine NPA tumble should give a well-separated (not near-degenerate)
    # null space: the second-smallest singular value should be a clear
    # fraction of the largest, not vanishingly small
    assert result.singular_values[1] / result.singular_values[-1] > 0.05


def test_principal_axis_spin_is_degenerate_for_inertia_recovery():
    """Spinning exactly about a single principal axis only constrains 'this
    axis is principal', not the full inertia ratios -- a two-dimensional
    null space, not one. The diagnostic is a second singular value that
    collapses toward zero alongside the first, unlike the well-separated
    case above."""
    state0 = RigidBodyState(
        position_m=np.zeros(3),
        velocity_m_s=np.zeros(3),
        quaternion=np.array([1.0, 0.0, 0.0, 0.0]),
        omega_body_rad_s=np.array([0.0, 0.0, 5.0]),  # exactly the major axis
    )
    traj = integrate(state0, m=1.0, i_body=I_ASYMMETRIC, dt=0.001, n_steps=2000)
    idx = np.arange(0, 2001, 20)
    rotations = traj.rotation_matrices()[idx]
    omegas = traj.omega_body_rad_s[idx]

    result = inertia_from_angular_momentum(rotations, omegas)
    relative_second_sv = result.singular_values[1] / result.singular_values[-1]
    assert relative_second_sv < 1e-3, (
        f"principal-axis spin should leave a near-2D null space, "
        f"got relative second singular value {relative_second_sv}"
    )


@pytest.mark.parametrize("c_true", [np.array([0.02, -0.015, 0.01]), np.array([0.05, 0.0, -0.03])])
def test_recovers_com_from_free_flight(c_true):
    """Simulate a tracked FEATURE POINT (not the COM itself -- that is what
    we are solving for) on a body whose true center of mass is offset from
    that feature by `c_true` in the body frame, and check the linear model
    recovers it."""
    m = 0.5
    state0 = RigidBodyState(
        position_m=np.array([0.0, 0.0, 1.0]),  # COM initial position
        velocity_m_s=np.array([2.0, 0.5, 4.0]),  # COM initial velocity
        quaternion=np.array([1.0, 0.0, 0.0, 0.0]),
        omega_body_rad_s=np.array([0.3, 4.0, 0.1]),  # genuine NPA tumble
    )
    traj = integrate(
        state0, m=m, i_body=I_ASYMMETRIC, dt=0.002, n_steps=400, force_world_fn=free_flight_force(m)
    )

    rotations = traj.rotation_matrices()
    # the tracked feature is defined to sit at the body-frame origin, so its
    # world position is COM_world(t) - R(t) @ c_true (see module docstring)
    feature_world = traj.position_m - np.einsum("fij,j->fi", rotations, c_true)

    result = com_from_free_flight(rotations, feature_world, traj.t_s)

    assert not result.fixed_axis_degenerate
    assert np.allclose(result.c_body, c_true, atol=1e-6)
    assert np.allclose(result.x0, state0.position_m, atol=1e-6)
    assert np.allclose(result.v0, state0.velocity_m_s, atol=1e-6)


def test_com_along_a_fixed_spin_axis_is_flagged_degenerate():
    """Uniform spin about a single fixed axis: the component of c ALONG
    that axis aliases with the initial position and must be flagged, not
    silently returned as if it were identifiable."""
    m = 0.5
    spin_axis = np.array([0.0, 0.0, 1.0])
    state0 = RigidBodyState(
        position_m=np.zeros(3),
        velocity_m_s=np.array([1.0, 0.0, 3.0]),
        quaternion=np.array([1.0, 0.0, 0.0, 0.0]),
        omega_body_rad_s=5.0 * spin_axis,  # pure spin about a principal (and world-fixed) axis
    )
    traj = integrate(
        state0, m=m, i_body=I_ASYMMETRIC, dt=0.002, n_steps=300, force_world_fn=free_flight_force(m)
    )
    rotations = traj.rotation_matrices()
    c_true = np.array([0.01, 0.02, 0.05])
    feature_world = traj.position_m - np.einsum("fij,j->fi", rotations, c_true)

    result = com_from_free_flight(rotations, feature_world, traj.t_s)
    assert result.fixed_axis_degenerate
    assert result.degenerate_axis_body is not None
    # the detected degenerate axis should align with the true spin axis (up to sign)
    alignment = abs(np.dot(result.degenerate_axis_body, spin_axis))
    assert alignment > 0.999
